<?php

// DO NOT EDIT! This file is auto generated by 'Shopware\Core\Framework\Feature'}
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return static function(ContainerConfigurator $configurator) {
    $configurator->parameters()->set(
        'shopware.features',
        array (
  'FEATURE_NEXT_1797' => false,
  'FEATURE_NEXT_11917' => false,
  'FEATURE_NEXT_12608' => true,
  'FEATURE_NEXT_16710' => false,
  'FEATURE_NEXT_13810' => false,
  'FEATURE_NEXT_13250' => false,
  'FEATURE_NEXT_16151' => false,
  'FEATURE_NEXT_16155' => false,
  'FEATURE_NEXT_14872' => false,
  'FEATURE_NEXT_15053' => false,
  'FEATURE_NEXT_14114' => false,
  'FEATURE_NEXT_12455' => false,
  'FEATURE_NEXT_15815' => false,
  'FEATURE_NEXT_8225' => false,
  'FEATURE_NEXT_14699' => false,
  'FEATURE_NEXT_6061' => false,
  'FEATURE_NEXT_15707' => false,
  'FEATURE_NEXT_15475' => false,
  'FEATURE_NEXT_14360' => false,
  'FEATURE_NEXT_15172' => false,
  'FEATURE_NEXT_15687' => false,
  'FEATURE_NEXT_6040' => false,
  'FEATURE_NEXT_14001' => false,
  'FEATURE_NEXT_7739' => false,
  'FEATURE_NEXT_16200' => false,
  'FEATURE_NEXT_8097' => false,
  'FEATURE_NEXT_16119' => false,
  'FEATURE_NEXT_15917' => false,
  'FEATURE_NEXT_15957' => false,
  'FEATURE_NEXT_13795' => false,
  'FEATURE_NEXT_13601' => false,
)
    );
};