<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Bo5Dxf\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Bo5Dxf/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Bo5Dxf.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Bo5Dxf\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container3Bo5Dxf\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '3Bo5Dxf',
    'container.build_id' => '11e2ddc7',
    'container.build_time' => 1631878109,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Bo5Dxf');
