<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdkYr0B\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdkYr0B/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdkYr0B.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdkYr0B\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerXdkYr0B\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'XdkYr0B',
    'container.build_id' => '34961f95',
    'container.build_time' => 1631868839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdkYr0B');
