<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKwCsOMT\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwCsOMT/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKwCsOMT.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKwCsOMT\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerKwCsOMT\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'KwCsOMT',
    'container.build_id' => 'fa0bcdd5',
    'container.build_time' => 1631877500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwCsOMT');
